Lint/EndAlignment:
  AlignWith: variable

Lint/Loop:
  Enabled: false

Metrics/BlockNesting:
  Max: 3

Metrics/ClassLength:
  Max: 500

Metrics/MethodLength:
  Max: 418

# We'd like to get this down to 72. But we have to start somewhere.
Metrics/LineLength:
  Max: 90

Style/CaseIndentation:
  IndentWhenRelativeTo: end

Style/CollectionMethods:
  PreferredMethods:
    find: detect

Style/DotPosition:
  EnforcedStyle: trailing

Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Style/Encoding:
  EnforcedStyle: when_needed

Style/HashSyntax:
  EnforcedStyle: hash_rockets # For legacy Ruby support

Style/IndentHash:
  EnforcedStyle: consistent

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/SpecialGlobalVars:
  Enabled: false

Style/TrivialAccessors:
  AllowDSLWriters: true
  AllowPredicates: true
  ExactNameMatch: true
